layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
#   linkedin: https://www.linkedin.com/in/vishal-kanakamamidi-218742170/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
#   website: https://vishalkanakamamidi.github.io/
#   youtube: https://www.youtube.com/channel/UCzHbVG0LxRRNTY8ZJbHKZOA?view_as=subscriber

topics:
  - name: Keras
    web_url: https://github.com/keras-team/keras
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c9/Keras_Logo.jpg

  - name: OpenCV
    web_url: https://github.com/opencv/opencv
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/OpenCV_Logo_with_text_svg_version.svg/1200px-OpenCV_Logo_with_text_svg_version.svg.png

  - name: Tensorflow
    web_url: https://github.com/tensorflow/tensorflow
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/2000px-TensorFlowLogo.svg.png
    
    
